# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 21:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_candidate', models.CharField(max_length=32, unique=True)),
                ('name_candidate', models.CharField(max_length=60)),
                ('summary', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateAchivement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achivement1', models.TextField(max_length=500)),
                ('achivement2', models.TextField(max_length=500)),
                ('achivement3', models.TextField(max_length=500)),
                ('achivement4', models.TextField(max_length=500)),
                ('achivement5', models.TextField(max_length=500)),
                ('id_candidate_achivement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achivement', to='pages.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('id_candidate_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='pages.Candidate')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=500, unique=True)),
                ('review', models.CharField(max_length=500, unique=True)),
                ('date_of_review', models.DateTimeField(auto_now_add=True)),
                ('id_candidate_reivew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pages.Candidate')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
